export const CLEAR_FOREGROUND = 'error.CLEAR_FOREGROUND';
export const SET_FOREGROUND = 'error.SET_FOREGROUND';
export const CLEAR_BACKGROUND = 'error.CLEAR_BACKGROUND';
export const SET_BACKGROUND = 'error.SET_BACKGROUND';