export const ADD = 'coins.ADD'
export const REMOVE = 'coins.REMOVE'
export const SET = 'coins.SET'
export const SET_REFERENCE_PRICE = 'coins.SET_REFERENCE_PRICE'
export const SET_REFERENCE_PRICES = 'coins.SET_REFERENCE_PRICES'