export const SET_BALANCE = "coin.SET_BALANCE"
export const SET_ORDERS = "coin.SET_ORDERS"
export const SET_ORDERBOOK = "coin.SET_ORDERBOOK"
export const SET_USER_TRADE_HISTORY = "coin.SET_TRADE_HISTORY"
export const ADD_TRADE = "coin.ADD_TRADE"
export const CLEAR_TRADES = "coin.CLEAR_TRADES"
export const CLEAR_BALANCES = "coin.CLEAR_BALANCES"
export const CANCEL_ORDER = "coin.CANCEL_ORDER"