export const SET_BALANCE = "coin.SET_BALANCE"
export const SET_ORDERS = "coin.SET_ORDERS"
export const SET_ORDERBOOK = "coin.SET_ORDERBOOK"
export const SET_TRADE_HISTORY = "coin.SET_TRADE_HISTORY"

export const CANCEL_ORDER = "coin.CANCEL_ORDER"

export const SET_BALANCE_UNAVAILABLE = "coin.SET_BALANCE_UNAVAILABLE"
export const SET_ORDERS_UNAVAILABLE = "coin.SET_ORDERS_UNAVAILABLE"
