export const LIMIT_ORDER = "LimitOrderJob"
export const SOFT_TRAILING_STOP = "SoftTrailingStop"
export const ALERT = "Alert"
export const STATUS_UPDATE = "StatusUpdateJob"
export const OCO = "OneCancelsOther"
export const SCRIPT = "ScriptJob"