export const OPEN_ALERTS = "ui.OPEN_ALERTS"
export const CLOSE_ALERTS = "ui.CLOSE_ALERTS"

export const OPEN_REFERENCE_PRICE = "ui.OPEN_REFERENCE_PRICE"
export const CLOSE_REFERENCE_PRICE = "ui.CLOSE_REFERENCE_PRICE"

export const RESET_PANELS = "ui.RESET_PANELS"
export const TOGGLE_PANEL_VISIBLE = "ui.TOGGLE_PANEL_VISIBLE"
export const TOGGLE_PANEL_ATTACHED = "ui.TOGGLE_PANEL_ATTACHED"
export const MOVE_PANEL = "ui.MOVE_PANEL"
export const RESIZE_PANEL = "ui.RESIZE_PANEL"

export const RESET_ALL_LAYOUTS = "ui.RESET_ALL_LAYOUTS"
export const UPDATE_LAYOUTS = "ui.UPDATE_LAYOUTS"
