export const ADD = "notifications.ADD"
export const CLEAR = "notifications.CLEAR"
export const DEFER_CALLBACK = "notifications.DEFER_CALLBACK"
export const COMPLETE_CALLBACK = "notifications.COMPLETE_CALLBACK"
export const REQUEST_CALLBACK = "notifications.REQUEST_CALLBACK"
