export const SET_OKTA_CONFIG = "auth.SET_OKTA_CONFIG"
export const INVALIDATE_LOGIN = "auth.INVALIDATE_LOGIN"
export const LOGIN = "auth.LOGIN"
export const LOGOUT = "auth.LOGOUT"
export const WHITELIST_UPDATE = "auth.WHITELIST_UPDATE"
