export const SET_TICKER = 'ticker.SET_TICKER'
export const SET_CONNECTION_STATE = 'ticker.SET_CONNECTION_STATE'
export const RESUBSCRIBE = 'ticker.RESUBSCRIBE'
export const CONNECT = 'ticker.CONNECT'
export const DISCONNECT = 'ticker.DISCONNECT'